[package]
name = "egui_pinger"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.28", features = [ "persistence" ] }
egui_extras = { version = "0.28", features = ["all_loaders"] }
tokio = { version = "1.38", features = ["rt-multi-thread", "macros", "time"] }
surge-ping = "0.8"
egui_plot = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"

[profile.release]
strip = true
opt-level = 'z'
lto = true
codegen-units = 1
#panic = 'abort'
